### ISSUE TITLE
install it and launch ?

### ISSUE THREAD

**Issue by fxw** [epam/OneDrive-L#5]
Hello Guys,

thanks for your pretty tools but how can I use it ? 

Install it and launch the tool ? 

Many thanks

**Comment by AndreiPashkin** [comment]
I'll add a description later today.

**Comment by fxw** [comment]
Many thanks for your help

FX

2017-07-18 11:42 GMT+02:00 Andrew Pashkin <notifications@github.com>:

**Comment by s-s-boika** [comment]
Not ready yet for usage. Under construction :)

**Comment by AndreiPashkin** [comment]
@s-s-boika, I thought the question was about development tools.

**Comment by fxw** [comment]
Hello Guys, it's just I want to launch the sync with ondrive with your tools. Can you explain me how can I do that ? I try to install the python script (via easy_install) but no binary files was created... Thanks for your help

**Comment by AndreiPashkin** [comment]
@fxw, sorry, I thought you are interested in contributing to the project and asking about how to setup the development environment.

At this moment the client is at early development stage and it's far from ready to be used by users.

**Comment by fxw** [comment]
OK, I can be a real beta tester ;)

**Comment by AndreiPashkin** [comment]
Stay tuned ;)
